-- Define buffer options for remaps
local bufopts = { noremap = true, silent = true }

-- Normal

-- Lower

vim.keymap.set('n', 'ё', '`', bufopts)
vim.keymap.set('n', 'й', 'q', bufopts)
vim.keymap.set('n', 'ц', 'w', bufopts)
vim.keymap.set('n', 'у', 'e', bufopts)
vim.keymap.set('n', 'к', 'r', bufopts)
vim.keymap.set('n', 'е', 't', bufopts)
vim.keymap.set('n', 'н', 'y', bufopts)
vim.keymap.set('n', 'г', 'u', bufopts)
vim.keymap.set('n', 'ш', 'i', bufopts)
vim.keymap.set('n', 'щ', 'o', bufopts)
vim.keymap.set('n', 'з', 'p', bufopts)
vim.keymap.set('n', 'х', '[', bufopts)
vim.keymap.set('n', 'ъ', ']', bufopts)

vim.keymap.set('n', 'ф', 'a', bufopts)
vim.keymap.set('n', 'ы', 's', bufopts)
vim.keymap.set('n', 'в', 'd', bufopts)
vim.keymap.set('n', 'а', 'f', bufopts)
vim.keymap.set('n', 'п', 'g', bufopts)
vim.keymap.set('n', 'р', 'h', bufopts)
vim.keymap.set('n', 'о', 'j', bufopts)
vim.keymap.set('n', 'л', 'k', bufopts)
vim.keymap.set('n', 'д', 'l', bufopts)
vim.keymap.set('n', 'ж', ';', bufopts)
vim.keymap.set('n', 'э', "'", bufopts)

vim.keymap.set('n', 'я', 'z', bufopts)
vim.keymap.set('n', 'ч', 'x', bufopts)
vim.keymap.set('n', 'с', 'c', bufopts)
vim.keymap.set('n', 'м', 'v', bufopts)
vim.keymap.set('n', 'и', 'b', bufopts)
vim.keymap.set('n', 'т', 'n', bufopts)
vim.keymap.set('n', 'ь', 'm', bufopts)
vim.keymap.set('n', 'б', ',', bufopts)
vim.keymap.set('n', 'ю', '.', bufopts)

-- Capitals

vim.keymap.set('n', 'Ё', '~', bufopts)
vim.keymap.set('n', 'Й', 'Q', bufopts)
vim.keymap.set('n', 'Ц', 'W', bufopts)
vim.keymap.set('n', 'У', 'E', bufopts)
vim.keymap.set('n', 'К', 'R', bufopts)
vim.keymap.set('n', 'Е', 'T', bufopts)
vim.keymap.set('n', 'Н', 'Y', bufopts)
vim.keymap.set('n', 'Г', 'U', bufopts)
vim.keymap.set('n', 'Ш', 'I', bufopts)
vim.keymap.set('n', 'Щ', 'O', bufopts)
vim.keymap.set('n', 'З', 'P', bufopts)
vim.keymap.set('n', 'Х', '{', bufopts)
vim.keymap.set('n', 'Ъ', '}', bufopts)

vim.keymap.set('n', 'Ф', 'A', bufopts)
vim.keymap.set('n', 'Ы', 'S', bufopts)
vim.keymap.set('n', 'В', 'D', bufopts)
vim.keymap.set('n', 'А', 'F', bufopts)
vim.keymap.set('n', 'П', 'G', bufopts)
vim.keymap.set('n', 'Р', 'H', bufopts)
vim.keymap.set('n', 'О', 'J', bufopts)
vim.keymap.set('n', 'Л', 'K', bufopts)
vim.keymap.set('n', 'Д', 'L', bufopts)
vim.keymap.set('n', 'Ж', ':', bufopts)
vim.keymap.set('n', 'Э', '"', bufopts)

vim.keymap.set('n', 'Я', 'Z', bufopts)
vim.keymap.set('n', 'Ч', 'X', bufopts)
vim.keymap.set('n', 'С', 'C', bufopts)
vim.keymap.set('n', 'М', 'V', bufopts)
vim.keymap.set('n', 'И', 'B', bufopts)
vim.keymap.set('n', 'Т', 'N', bufopts)
vim.keymap.set('n', 'Ь', 'M', bufopts)
vim.keymap.set('n', 'Б', '<', bufopts)
vim.keymap.set('n', 'Ю', '>', bufopts)


-- Visual

-- Lower

vim.keymap.set('v', 'ё', '`', bufopts)
vim.keymap.set('v', 'й', 'q', bufopts)
vim.keymap.set('v', 'ц', 'w', bufopts)
vim.keymap.set('v', 'у', 'e', bufopts)
vim.keymap.set('v', 'к', 'r', bufopts)
vim.keymap.set('v', 'е', 't', bufopts)
vim.keymap.set('v', 'н', 'y', bufopts)
vim.keymap.set('v', 'г', 'u', bufopts)
vim.keymap.set('v', 'ш', 'i', bufopts)
vim.keymap.set('v', 'щ', 'o', bufopts)
vim.keymap.set('v', 'з', 'p', bufopts)
vim.keymap.set('v', 'х', '[', bufopts)
vim.keymap.set('v', 'ъ', ']', bufopts)

vim.keymap.set('v', 'ф', 'a', bufopts)
vim.keymap.set('v', 'ы', 's', bufopts)
vim.keymap.set('v', 'в', 'd', bufopts)
vim.keymap.set('v', 'а', 'f', bufopts)
vim.keymap.set('v', 'п', 'g', bufopts)
vim.keymap.set('v', 'р', 'h', bufopts)
vim.keymap.set('v', 'о', 'j', bufopts)
vim.keymap.set('v', 'л', 'k', bufopts)
vim.keymap.set('v', 'д', 'l', bufopts)
vim.keymap.set('v', 'ж', ';', bufopts)
vim.keymap.set('v', 'э', "'", bufopts)

vim.keymap.set('v', 'я', 'z', bufopts)
vim.keymap.set('v', 'ч', 'x', bufopts)
vim.keymap.set('v', 'с', 'c', bufopts)
vim.keymap.set('v', 'м', 'v', bufopts)
vim.keymap.set('v', 'и', 'b', bufopts)
vim.keymap.set('v', 'т', 'n', bufopts)
vim.keymap.set('v', 'ь', 'm', bufopts)
vim.keymap.set('v', 'б', ',', bufopts)
vim.keymap.set('v', 'ю', '.', bufopts)

-- Capitals

vim.keymap.set('v', 'Ё', '~', bufopts)
vim.keymap.set('v', 'Й', 'Q', bufopts)
vim.keymap.set('v', 'Ц', 'W', bufopts)
vim.keymap.set('v', 'У', 'E', bufopts)
vim.keymap.set('v', 'К', 'R', bufopts)
vim.keymap.set('v', 'Е', 'T', bufopts)
vim.keymap.set('v', 'Н', 'Y', bufopts)
vim.keymap.set('v', 'Г', 'U', bufopts)
vim.keymap.set('v', 'Ш', 'I', bufopts)
vim.keymap.set('v', 'Щ', 'O', bufopts)
vim.keymap.set('v', 'З', 'P', bufopts)
vim.keymap.set('v', 'Х', '{', bufopts)
vim.keymap.set('v', 'Ъ', '}', bufopts)

vim.keymap.set('v', 'Ф', 'A', bufopts)
vim.keymap.set('v', 'Ы', 'S', bufopts)
vim.keymap.set('v', 'В', 'D', bufopts)
vim.keymap.set('v', 'А', 'F', bufopts)
vim.keymap.set('v', 'П', 'G', bufopts)
vim.keymap.set('v', 'Р', 'H', bufopts)
vim.keymap.set('v', 'О', 'J', bufopts)
vim.keymap.set('v', 'Л', 'K', bufopts)
vim.keymap.set('v', 'Д', 'L', bufopts)
vim.keymap.set('v', 'Ж', ':', bufopts)
vim.keymap.set('v', 'Э', '"', bufopts)

vim.keymap.set('v', 'Я', 'Z', bufopts)
vim.keymap.set('v', 'Ч', 'X', bufopts)
vim.keymap.set('v', 'С', 'C', bufopts)
vim.keymap.set('v', 'М', 'V', bufopts)
vim.keymap.set('v', 'И', 'B', bufopts)
vim.keymap.set('v', 'Т', 'N', bufopts)
vim.keymap.set('v', 'Ь', 'M', bufopts)
vim.keymap.set('v', 'Б', '<', bufopts)
vim.keymap.set('v', 'Ю', '>', bufopts)
